/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.example.app;

import org.junit.jupiter.api.Test;

import java.util.Random;

import static org.junit.jupiter.api.Assertions.assertEquals;

class MessageUtilsTest {
    @Test void testGetMessage() {
        assertEquals(new Random().nextInt(), new Random().nextInt());
    }
}
